
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Reproductor
{

using System;
    using System.Collections.Generic;
    
public partial class Tracks
{

    public long ID_Track { get; set; }

    public string Track { get; set; }

}

}
